[tool.poetry]
name = "MushroomClassifier"
version = "0.8.0"
description = "EffecientNet fine tuned on 80 000 images of ~1400 species with deployable framework"
authors = ["Graham Broughton <broughton.graham@gmail.com>"]
readme = "README.md"
packages = [
	{include = "training", from = "src"},
	{include = "deployment", from = "src"}]

[tool.poetry.dependencies]
python = {version=">3", source = "pyp"}
tensorflow = {version="*", source = "pyp"}
Flask = {version="*", source = "pyp"}
Pillow = {version="*", source = "pyp"}
PyYAML = {version="*", source = "pyp"}
pandas = {version="*", source = "pyp"}
tensorflow-addons = {version="*", source = "pyp"}
regex = {version="*", source = "pyp"}
wget = {version="*", source = "pyp"}


[[tool.poetry.source]]
name = "packagr"
url = "https://api.packagr.app/G9aT9cXx"
default = false
secondary = true

[[tool.poetry.source]]
name = "pyp"
url = "https://pypi.org/"
default = true
secondary = false

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
