[tool.poetry]
name = "MushroomClassifier"
version = "0.4.0"
description = "EffecientNet fine tuned on 80 000 images of ~1400 species with deployable framework"
authors = ["Graham Broughton <broughton.graha@gmail.com>"]
readme = "README.md"
packages = [
	{include = "training", from = "src"},
	{include = "deployment", from = "src"}]

[tool.poetry.dependencies]
python = ">=3.8,<3.11"
tensorflow = "^2.8"
Flask = "^1.1.4"
Pillow = "^9.2.0"
PyYAML = "^6"
pandas = "^1.4.4"
tensorflow-addons = "^0.16.1"
regex = "^2022"
wget = "^3.2"


[tool.poetry.group.dev.dependencies]
pendulum = "^2.1.2"
pytest = "^7.1.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
