# PATHS
path       : 'drive/MyDrive/mushroom_classification/new/'

# NN
INITIAL_LR_RATE    : 0.001
LR_DECAY_FACTOR    : 0.985
EPOCHS_PER_DECAY   : 2
ES_PATIENCE        : 1

IMAGE_SIZE         : [512, 512]
DROPOUT_PERCENT    : 0.2
BATCH_SIZE         : 64