#### EXPERIMENT PARAMS

FINAL_SAVE_DIR          : "gs://tpubucketgb/final_model/run1


#### DATA PARAMS

TRAINING_DIR            : "gs://medium_mush/GM_all_yolo_train.csv"
VAL_DIR                 : "gs://medium_mush/GM_all_yolo_val.csv"
NUM_CLASSES             : 2
LABEL_COLUMN_NAME	: "supercategory"
IMAGE_COLUMN_NAME 	: "file_path"


#### TRAINING PARAMS
BATCH_SIZE              : 64
NUM_EPOCHS              : 30

# learning rate params
INITIAL_LEARNING_RATE   : 0.05
LR_DECAY_FACTOR         : 0.94
EPOCHS_PER_DECAY        : 2


#### MODEL PARAMS
MODEL_NAME              : "df.keras.applications.EffecientNetV2L"
IMAGE_SIZE              : [256, 256]
DROPOUT_PERCENT         : 0.5
PRETRAINED_WEIGHTS      : "imagenet"

# optimizer
OPTIMIZER_NAME		: "rmsprop"
RMSPROP_RHO		: 0.9
RMSPROP_MOMENTUM	: 0.9
RMSPROP_EPSILON		: 1.0

# loss
LOSS			: "binary_crossentropy"

TPU                     : True